---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 Instance
      ec2:
        key_name: your_key_pair_name
        instance_type: t2.micro
        image: ami-12345678  # Replace with your desired Amazon Machine Image (AMI) ID
        region: your_aws_region
        vpc_subnet_id: your_subnet_id
        assign_public_ip: yes
        count: 1
        wait: yes
      register: ec2

    - name: Add new instance to dynamic inventory
      add_host:
        name: "{{ item.public_ip }}"
        groups: new_instances
      with_items: "{{ ec2.instances }}"